from django.urls import path
from . import views

urlpatterns = [

    path('objective-list-view-api/', views.ObjectiveListView.as_view(), name='objective-list-view-api'),
    path('objective-creation-api/', views.ObjectiveCreationView.as_view(), name='objective-creation-api'),    
    path('objective-update-api/<int:obj_id>/', views.ObjectiveUpdateView.as_view(), name='objective-update-api'),
    path('view-key-result-api/', views.ViewKeyResultView.as_view(), name='view-key-result-api'),
    path('filter-key-result-api/', views.FilterKeyResultView.as_view(), name='filter-key-result-api'),
    path('key-result-create-api/', views.KeyResultCreateView.as_view(), name='key-result-create-api'),
    path('key_result_create_or_update-api/<int:kr_id>/', views.KeyResultCreateOrUpdateView.as_view(), name='key_result_create_or_update_view_with_id'),
    path('add-assignees-api/<int:obj_id>/', views.AddAssigneesView.as_view(), name='add-assignees-api'),
    path('objective-delete-api/<int:obj_id>/', views.ObjectiveDeleteView.as_view(), name='objective-delete-api'),
    path('objective-manager-remove-api/<int:obj_id>/<int:manager_id>/',views.ObjectiveManagerRemoveView.as_view(), name='objective-manager-remove-api'),
    path('key-result-remove-api/<int:obj_id>/<int:kr_id>/', views.KeyResultRemoveView.as_view(), name='key-result-remove-api'),
    path('assignees-remove-api/<int:obj_id>/<int:emp_id>/', views.AssigneesRemoveView.as_view(), name='assignees-remove-api'),
    path('objective-list-search-api/', views.ObjectiveListSearchView.as_view(), name='objective-list-search-api'),
    path('objective-dashboard-api/', views.ObjectiveDashboardView.as_view(), name='objective_dashboard-api'),
    path('objective-history-api/<int:emp_obj_id>/', views.ObjectiveHistoryView.as_view(), name='objective-history-api'),
    path('objective-detailed-view-activity-api/<int:id>/', views.ObjectiveDetailedViewActivity.as_view(), name='objective-detailed-view-activity-api'),
    path('objective-detailed-view-comment-api/<int:id>/', views.ObjectiveDetailedViewComment.as_view(), name='objective-detailed-view-comment-api'),
    path('emp-objective-search-api/<int:obj_id>/', views.EmpObjectiveSearchView.as_view(), name='emp-objective-search-api'),
    path('kr-table-view-api/<int:emp_objective_id>/', views.KRTableView.as_view(), name='kr-table-view-api'),
    path('objective-detailed-view-objective-status-api/<int:id>/', views.ObjectiveDetailedViewObjectiveStatus.as_view(), name='objective-detailed-view-objective-status-api'),
    path('objective_detailed_view_key_result_status/<int:obj_id>/<int:kr_id>/', views.ObjectiveDetailedViewKeyResultStatus.as_view(), name='objective_detailed_view_key_result_status'),
    path('objective-detailed-view-current-value-api/<int:kr_id>/', views.ObjectiveDetailedViewCurrentValue.as_view(), name='objective-detailed-view-current-value-api'),
    path('objective-archive-api/<int:id>/', views.ObjectiveArchiveView.as_view(), name='objective_archive'),
    path('view-employee-objective-api/<int:emp_obj_id>/', views.ViewEmployeeObjective.as_view(), name='view-employee-objective-api'),
    path('create-employee-objective-api/', views.CreateEmployeeObjectiveView.as_view(), name='create-employee-objective-api'),
    path('update-employee-objective-api/<int:emp_obj_id>/', views.UpdateEmployeeObjectiveView.as_view(), name='update-employee-objective-api'),
    path('archive-employee-objective-api/<int:emp_obj_id>/', views.ArchiveEmployeeObjectiveView.as_view(), name='archive-employee-objective-api'),
    path('delete-employee-objective-api/<int:emp_obj_id>/', views.DeleteEmployeeObjectiveView.as_view(), name='delete-employee-objective-api'),
    path('change-employee-objective-status-api/', views.ChangeEmployeeObjectiveStatusView.as_view(), name='change-employee-objective-status-api'),
    path('key-result-view-api/', views.KeyResultView.as_view(), name='key-result-view-api'),
    path('key-result-creation-api/<str:obj_id>/<str:obj_type>/', views.KeyResultCreationView.as_view(), name='key-result-creation-api'),
    path('key-result-update-api/<int:id>/', views.KeyResultUpdateView.as_view(), name='key_result_update'),
    path('feedback-creation-api/', views.FeedbackCreationView.as_view(), name='feedback-creation-api'),
    path('feedback-update-api/<int:id>/', views.FeedbackUpdateView.as_view(), name='feedback-update-api'), 
    path('feedback-list-search-api/', views.FeedbackListSearchView.as_view(), name='feedback-list-search-api'),
    path('feedback-list-view-api/', views.FeedbackListView.as_view(), name='feedback-list-view-api'),
    path('feedback-detailed-view-api/<int:id>/', views.FeedbackDetailedView.as_view(), name='feedback-detailed-view-api'),
    path('feedback-detailed-view-answer-api/<int:id>/<int:emp_id>/', views.FeedbackDetailedViewAnswer.as_view(), name='feedback-detailed-view-answer-api'),
    path('feedback-answer-get-api/<int:id>/', views.FeedbackAnswerGet.as_view(), name='feedback-answer-get-api'), 
    path('feedback-answer-post-api/<int:id>/', views.FeedbackAnswerPost.as_view(), name='feedback-answer-post-api'),
    path('feedback-answer-view-api/<int:id>/', views.FeedbackAnswerView.as_view(), name='feedback-answer-view-api'),
    path('feedback-delete-api/<int:id>/', views.FeedbackDeleteView.as_view(), name='feedback-delete-api'),
    path('feedback-detailed-view-status-api/<int:id>/', views.FeedbackDetailedViewStatus.as_view(), name='feedback-detailed-view-status-api'),
    path('feedback-overview-api/<int:obj_id>/', views.FeedbackOverviewView.as_view(), name='feedback-overview-api'),
    path('feedback-archive-api/<int:id>/', views.FeedbackArchiveView.as_view(), name='feedback-archive-api'),
    path('get-colleagues-api/', views.GetColleaguesView.as_view(), name='get-colleagues-api'),
    path('feedback-status-api/', views.FeedbackStatusView.as_view(), name='feedback-status-api'),
    path('question-creation-api/<int:id>/', views.QuestionCreationAPIView.as_view(), name='question-creation-api'),
    path('question-view-api/<int:id>/', views.QuestionView.as_view(), name='question-view-api'),
    path('question-update-api/<int:temp_id>/<int:q_id>/', views.QuestionUpdateView.as_view(), name='question-update-api'),
    path('question-delete-api/<int:id>/', views.QuestionDeleteView.as_view(), name='question-delete-api'),
    path('question-template-creation-api/', views.QuestionTemplateCreationView.as_view(), name='question-template-creation-api'),
    path('question-template-view-api/', views.QuestionTemplateView.as_view(), name='question-template-view-api'),
    path('question-template-detailed-view-api/<int:template_id>/', views.QuestionTemplateDetailedView.as_view(), name='question-template-detailed-view-api'),
    path('question-template-creation-api/', views.QuestionTemplateCreationView.as_view(), name='question-template-creation-api'),
    path('question-template-update-api/<int:template_id>/', views.QuestionTemplateUpdateAPIView.as_view(), name='question-template-update-api'),
    path('question-template-delete-api/<int:template_id>/', views.QuestionTemplateDeleteView.as_view(), name='question-template-delete-api'),
    path('period-view-api/', views.PeriodView.as_view(), name='period-view-api'),
    path('period-create-api/', views.PeriodCreateView.as_view(), name='period-create-api'),
    path('period-update-api/<int:period_id>/', views.PeriodUpdateView.as_view(), name='period-update-api'),
    path('period-delete-api/<int:period_id>/', views.PeriodDeleteView.as_view(), name='period-delete-api'),
    path('dashboard-view-api/', views.DashboardView.as_view(), name='dashboard-view-api'),
    path('objective-bulk-archive-api/', views.ObjectiveBulkArchiveView.as_view(), name='objective-bulk-archive-api'),
    path('objective-bulk-delete-api/', views.ObjectiveBulkDeleteView.as_view(), name='objective-bulk-delete-api'),
    path('feedback-bulk-archive-api/', views.FeedbackBulkArchiveView.as_view(), name='feedback-bulk-archive-api'),
    path('feedback-bulk-delete-api/', views.FeedbackBulkDeleteView.as_view(), name='feedback-bulk-delete-api'),
    path('objective-select-api/', views.ObjectiveSelectView.as_view(), name='objective-select-api'),
    path('objective-select-filter-api/', views.ObjectiveSelectFilterView.as_view(), name='objective-select-filter-api'),
    path('anonymous-feedback-add-api/', views.AnonymousFeedbackAddView.as_view(), name='anonymous-feedback-add-api'),
    path('edit-anonymous-feedback-api/<int:obj_id>/', views.EditAnonymousFeedbackView.as_view(), name='edit-anonymous-feedback-api'),
    path('archive-anonymous-feedback-api/<int:obj_id>/', views.ArchiveAnonymousFeedbackView.as_view(), name='archive-anonymous-feedback-api'),
    path('delete-anonymous-feedback-api/<int:obj_id>/', views.DeleteAnonymousFeedbackView.as_view(), name='delete-anonymous-feedback-api'),
    path('view-single-anonymous-feedback-api/<int:obj_id>/', views.ViewSingleAnonymousFeedbackView.as_view(), name='view-single-anonymous-feedback-api'),
    path('employee-keyresult-creation-api/<int:emp_obj_id>/', views.EmployeeKeyResultCreationView.as_view(), name='employee-keyresult-creation-api'),
    path('employee-keyresult-update-api/<int:kr_id>/', views.EmployeeKeyResultUpdateView.as_view(), name='employee-keyresult-update-api'),
    path('delete-employee-keyresult-api/<int:kr_id>/', views.DeleteEmployeeKeyResultView.as_view(), name='delete-employee-keyresult-api'),
    path('employee-keyresult-update-status-api/<int:kr_id>/', views.EmployeeKeyResultUpdateStatusView.as_view(), name='employee-keyresult-update-status-api'),
    path('key-result-current-value-update-api/', views.KeyResultCurrentValueUpdateView.as_view(), name='key-result-current-value-update-api'),
    path('get-keyresult-data-api/', views.KeyResultDataView.as_view(), name='get-keyresult-data-api'),
    path('view-meetings-api/', views.ViewMeetingsView.as_view(), name='view-meetings-api'),
    path('create-meetings-api/', views.CreateMeetingsView.as_view(), name='create-meetings-api'),
    path('archive-meetings-api/<int:id>/', views.ArchiveMeetingsView.as_view(), name='archive-meetings-api'),
    path('meeting_-anager-remove-api/<int:meet_id>/<int:manager_id>/', views.MeetingManagerRemoveView.as_view(), name='meeting_-anager-remove-api'),
    path('meeting-employee-remove-api/<int:meet_id>/<int:employee_id>/',views. MeetingEmployeeRemoveView.as_view(), name='meeting-employee-remove-api'), 
    path('filter-meetings-api/', views.FilterMeetingsView.as_view(), name='filter-meetings-api'),
    path('add-response-api/<int:id>/', views.AddResponseView.as_view(), name='add-response-api'),
    path('meeting-answer-get-api/<int:id>/', views.MeetingAnswerGetView.as_view(), name='meeting-answer-get-api'),
    path('meeting-answer-post-api/<int:id>/',views. MeetingAnswerPostView.as_view(), name='meeting-answer-post-api'),
    path('meeting-answer-view-api/<int:id>/<int:emp_id>/', views.MeetingAnswerView.as_view(), name='meeting-answer-view-api'),
    path('meeting-question-template-view-api/<int:meet_id>/',views. MeetingQuestionTemplateView.as_view(), name='meeting-question-template-view-api'),
    path('meeting-single-view-api/<int:id>/', views.MeetingSingleView.as_view(), name='meeting-single-view-api'),
    path('performance-tab-api/<int:emp_id>/', views.PerformanceTabView.as_view(), name='performance-tab-api'),
    path('dashboard-feedback-answer-api/', views.DashboardFeedbackAnswerView.as_view(), name='dashboard-feedback-answer-api'),





]
