services:
  - type: web
    name: HR-Payroll
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn horilla.wsgi:application
