from django.urls import path
from . import views
from base.models import RotatingShift

urlpatterns = [
    path('shift-requests-create-api/', views.ShiftRequestAPIView.as_view(), name='shift-requests-create-api'),
    path('shift-requests-update-api/<int:shift_request_id>/', views.ShiftRequestUpdateAPIView.as_view(), name='shift-requests-update-api'),
    path('shift-requests-cancel-api/<int:shift_request_id>/', views.ShiftRequestCancelAPIView.as_view(), name='shift-requests-cancel-api'),
    path('shift-requests-approve-api/<int:shift_request_id>/', views.ShiftRequestApproveAPIView.as_view(), name='shift-requests-approve-api'),
    path('shift-requests-delete-api/<int:shift_request_id>/', views.ShiftRequestDeleteAPIView.as_view(), name='shift_request_delete'),
    path('company-create-api/', views.CompanyCreateView.as_view(), name='company-create-api'),
    path('companies-view-api/', views.CompanyListView.as_view(), name='companies-view-api'),
    path('company-update-api/<int:id>/', views.CompanyUpdateView.as_view(), name='company-update-api'),
    path('department-create-api/', views.DepartmentCreateView.as_view(), name='department-create-api'),
    path('departments-view-api/', views.DepartmentListView.as_view(), name='departments-view-api'),
    path('department-update-api/<int:id>/', views.DepartmentUpdateView.as_view(), name='department-update-api'), 
    path('job-positions-view-api/', views.JobPositionListCreateView.as_view(), name='job_positions-view-api'),
    path('job-position-creation-api/', views.JobPositionCreationView.as_view(), name='jobposition-creation-api'),
    path('job-position-update-api/<int:id>/', views.JobPositionUpdateAPIView.as_view(), name='jobposition-update-api'),
    path('job-role-create-api/', views.JobRoleCreateAPIView.as_view(), name='job-role-create-api'),
    path('job-role-view-api/', views.JobRoleView.as_view(), name='job-role-view-api'),
    path('job-role-update-api/<int:id>/', views.JobRoleUpdateView.as_view(), name='job-role-update-api'),
    path('work-type-create-api/', views.WorkTypeCreateView.as_view(), name='work-type-create-api'),
    path('work-type-view-api/', views.WorkTypeView.as_view(), name='work-type-view-api'),
    path('work-type-update-api/<int:id>/', views.WorkTypeUpdateAPIView.as_view(), name='work-type-update-api'),
    path('announcements-views-api/', views.AnnouncementAPIView.as_view(), name='announcements-views-api'),
    path('announcements-viewed-by-api/', views.ViewedByAPIView.as_view(), name='announcements-viewed-by-api'),
    path('create-announcement-api/', views.AnnouncementCreateAPIView.as_view(), name='create-announcement-api'),
    path('delete-announcement-api/<int:anoun_id>/', views.AnnouncementDeleteAPIView.as_view(), name='delete-announcement-api'),
    path('update-announcement-api/<int:anoun_id>/', views.AnnouncementUpdateAPIView.as_view(), name='update-announcement-api'),
    path('create-announcement-comment-api/<int:anoun_id>/', views.AnnouncementCommentCreateAPIView.as_view(), name='create-announcement-comment-api'),
    path('view-announcement-comments-api/<int:anoun_id>/', views.AnnouncementCommentListAPIView.as_view(), name='view-announcement-comments-api'),
    path('delete-announcement-comment-api/<int:comment_id>/', views.AnnouncementCommentDeleteAPIView.as_view(), name='delete-announcement-comment-api'),
    path('announcement-single-view-api/<int:anoun_id>/', views.AnnouncementSingleAPIView.as_view(), name='announcement-single-view-api'),
    path('action-types-api/', views.ActiontypeListAPIView.as_view(), name='action-types-api'),
    path('create-action-type-api/', views.ActiontypeCreateAPIView.as_view(), name='create-action-type-api'),
    path('update-action-type-api/<int:act_id>/', views.ActiontypeUpdateAPIView.as_view(), name='update-action-type-api'),
    path('delete-action-type-api/<int:act_id>/', views.ActiontypeDeleteAPIView.as_view(), name='delete-action-type-api'),
    path('create-shiftrequest-comment-api/<int:shift_id>/', views.ShiftRequestCommentCreateAPIView.as_view(), name='create-shiftrequest-comment-api'),
    path('view-shift-comments-api/<int:shift_id>/', views.ShiftRequestCommentListAPIView.as_view(), name='view-shift-comments-api'),
    path('delete-shift-comment-file-api/', views.DeleteShiftCommentFileAPIView.as_view(), name='delete-shift-comment-file-api'),
    path('view-work-type-comments-api/<int:work_type_id>/', views.WorkTypeRequestCommentListAPIView.as_view(), name='view-work-type-comments-api'), 
    path('delete-work-type-comment-file-api/', views.DeleteWorkTypeCommentFileAPIView.as_view(), name='delete-work-type-comment-file-api'),
    path('delete-shiftrequest-comment-api/<int:comment_id>/', views.DeleteShiftRequestCommentAPIView.as_view(), name='delete-shiftrequest-comment-api'),
    path('create-worktyperequest-comment-api/<int:worktype_id>/', views.WorkTypeRequestCommentCreateAPIView.as_view(), name='create-worktyperequest-comment-api'),
    path('delete-worktyperequest-comment-api/<int:comment_id>/',views.WorkTypeRequestCommentDeleteAPIView.as_view(), name='delete-worktyperequest-comment-api'),
    path('employee-shift-schedule-api/', views.EmployeeShiftScheduleAPIView.as_view(), name='employee-shift-schedule-api'),
    path('employee-shift-schedule-create-api/', views.EmployeeShiftScheduleCreateAPIView.as_view(), name='employee-shift-schedule-create-api'), 
    path('employee-shift-schedule-update-api/<int:id>/', views.EmployeeShiftScheduleUpdateAPIView.as_view(), name='employee-shift-schedule-update-api'), 
    path('rotating-shifts-api/', views.RotatingShiftView.as_view(), name='rotating_shifts-api'),
    path('rotating-shifts-create-api/', views.RotatingShiftCreate.as_view(), name='rotating-shifts-create-api'),
    path('rotating-shift-update-api/<int:id>/', views.RotatingShiftUpdate.as_view(), name='rotating-shift-update-api'),
    path('rotating-shift-object-delete-api/<int:obj_id>/', views.ObjectDelete.as_view(), name='rotating-shift-object-delete-api', kwargs={'model': RotatingShift}),
    path('employee-shift-schedule-delete-api/<int:obj_id>/', views.EmployeeShiftDelete.as_view(), name='employee-shift-schedule-delete-api'),
    path('employee-shift-delete/<int:obj_id>/', views.EmployeeShiftDelete.as_view(), name='employee-shift-delete'),
    path('employee-types-api/', views.EmployeeTypeView.as_view(), name='employee-types-api'),
    path('employee-types-create-api/', views.EmployeeTypeCreate.as_view(), name='employee-types-create-api'),
    path('employee-types-update-api/<int:id>/', views.EmployeeTypeUpdate.as_view(), name='employee-types-update-api'),
    path('employee-type-delete-api/<int:obj_id>/', views.EmployeeTypeDelete.as_view(), name='employee-type-delete-api'),
    path('tags-view-api/', views.TagView.as_view(), name='tags-view-api'),
    path('helpdesk-tags-api/', views.HelpdeskTagView.as_view(), name='helpdesk-tags-api'),


]
