from django.urls import path
from . import views

urlpatterns = [


    path('leave-type-create-api/', views.LeaveTypeCreation.as_view(), name='leave-type-create-api'),
    path('leave-create-api/', views.LeaveRequestAPIView.as_view(), name='leave_request_api'),
    path('leave-types-view-api/', views.LeaveTypeAPIView.as_view(), name='leave_type_api'),
    path('leave-type-individual-api/<int:id>/', views.LeaveTypeIndividualView.as_view(), name='leave-type-individual-view-api'),
    path('leave-type-filter-api/', views.LeaveTypeFilterView.as_view(), name='leave-type-filter-api'),
    path('leave-type-update-api/<int:id>/', views.LeaveTypeUpdateView.as_view(), name='leave-type-update-api'), 
    path('leave-type-delete-api/<int:obj_id>/', views.LeaveTypeDeleteView.as_view(), name='leave-type-delete-api'), 
    path('get-employee-leave-types-api/', views.GetEmployeeLeaveTypesView.as_view(), name='get-employee-leave-types-api'),
    path('multiple-approvals-check-api/<int:id>/', views.MultipleApprovalsCheckView.as_view(), name='multiple-approvals-check-api'),
    #path('leave-request-create-api/', views.LeaveRequestCreationAPI.as_view(), name='leave-request-create-api'),
    path('leave-requests-api/', views.LeaveRequestView.as_view(), name='leave-requests-api'),
    path('leave-requests-with-interview-api/', views.LeaveRequestWithInterviewView.as_view(), name='leave-requests-with-interview-api'),
    path('leave-requests-filter-api/', views.LeaveRequestFilterView.as_view(), name='leave-requests-filter-api'),
    path('leave-requests-update-api/<int:id>/', views.LeaveRequestUpdateAPI.as_view(), name='leave-requests-update-api'),
    path('leave-requests-delete-api/<int:id>/', views.LeaveRequestDeleteView.as_view(), name='leave-requests-delete-api'),
    path('leave-requests-approve-api/<int:id>/', views.LeaveRequestApproveAPI.as_view(), name='leave-requests-approve-api'),
    path('leave-requests-bulk-approve-api/', views.LeaveRequestBulkApproveView.as_view(), name='leave-requests-bulk-approve-api'),
    path('leave-requests-bulk-reject-api/', views.LeaveRequestBulkRejectView.as_view(), name='leave-requests-bulk-reject-api'),
    path('leave-requests-cancel-api/<int:id>/', views.LeaveRequestCancelView.as_view(), name='leave-requests-cancel-api'),
    path('user-leave-cancel-api/<int:id>/', views.UserLeaveCancelView.as_view(), name='user-leave-request-api'),
    path('one-request-view-api/<int:id>/', views.OneRequestView.as_view(), name='one-request-view-api'),
    path('leave-assign-one-api/<int:id>/', views.LeaveAssignOneAPI.as_view(), name='leave-assign-one-api'),
    path('leave-assign-view-api/', views.LeaveAssignView.as_view(), name='leave-assign-view-api'),
    path('available-leave-single-view-api/<int:obj_id>/', views.AvailableLeaveSingleView.as_view(), name='available-leave-view-api'),
    path('leave-assign-filter-api/', views.LeaveAssignFilterView.as_view(), name='leave-assign-filter-api'),
    path('leave-assign-api/', views.LeaveAssignAPIView.as_view(), name='leave-assign-api'),
   
    path('available-leave-update-api/<int:id>/', views.AvailableLeaveUpdateView.as_view(), name='available-leave-update-api'),
    path('leave_assign_delete-api/<int:obj_id>/', views.LeaveAssignDeleteView.as_view(), name='leave_assign_delete_api'),
    path('leave-assign-bulk-delete-api/', views.LeaveAssignBulkDeleteView.as_view(), name='leave-assign-bulk-delete-api'),
   
    path('assign-leave-type-excel-api/', views.AssignLeaveTypeExcelView.as_view(), name='assign-leave-type-excel-api'),
    path('assign-leave-type-import-api/', views.AssignLeaveTypeImportView.as_view(), name='assign-leave-type-import-api'),
    path('assign-leave-export-api/',views.AssignedLeavesExportView.as_view(), name='assign-leave-export-api'),
    path('job-positions-api/', views.GetJobPositionsView.as_view(), name='get-job-positions-api'),
    path('restrict-creation-api/', views.RestrictCreationView.as_view(), name='restrict-creation-api'),
    path('restrict-view-api/',views.RestrictView.as_view(), name='restrict-view-api'),
    path('restrict-filter-api/', views.RestrictFilterView.as_view(), name='restrict-filter-api'),
    path('restrict-update-api/<int:id>/', views.RestrictUpdateView.as_view(), name='restrict-update-api'),
    path('restrict-delete-api/<int:id>/', views.RestrictDeleteView.as_view(), name='restrict-delete-api'),
    path('restrict_days_bulk_delete-api/', views.RestrictDaysBulkDelete.as_view(), name='restrict-days-bulk-delete-api'),
    path('restrict_day_select-api/', views.RestrictDaySelect.as_view(), name='restrict-day-select-api'),
    path('user-leave-request-api/<int:id>/', views.UserLeaveRequest.as_view(), name='user-leave-request-api'),
    path('user_leave_request_update-api/<int:id>/', views.UserLeaveRequestUpdate.as_view(), name='user-leave-request-update-api'),
    path('user_leave_request_delete-api/<int:id>/', views.UserLeaveRequestDelete.as_view(), name='user-leave-request-delete-api'),
    path('user_leave_view-api/', views.UserLeaveView.as_view(), name='user_leave_view_api'),
    path('user_leave_filter-api/', views.UserLeaveFilter.as_view(), name='user_leave_filter'),
    path('user_leave_request_view-api/', views.UserLeaveRequestView.as_view(), name='user_leave_request_view_api'),
    path('user_leave_request_filter-api/', views.UserLeaveRequestFilterView.as_view(), name='user_leave_request_filter_api'),
    path('user_leave_request_one-api/<int:id>/', views.UserLeaveRequestOne.as_view(), name='user_leave_request_one_api'),
    path('employee_leave_today-api/', views.EmployeeLeaveToday.as_view(), name='employee_leave_today_api'),
    path('overall_leave-api/', views.OverallLeaveView.as_view(), name='overall_leave_api'),
    path('dashboard-api/', views.DashboardView.as_view(), name='dashboard_api'),
    path('employee_dashboard-api/', views.EmployeeDashboardView.as_view(), name='employee_dashboard_api'),
    path('dashboard_leave_request-api/', views.DashboardLeaveRequestView.as_view(), name='dashboard_leave_request_api'),
    path('available_leave_chart-api/', views.AvailableLeaveChartView.as_view(), name='available_leave_chart_api'),
    path('employee_leave_chart-api/', views.EmployeeLeaveChartView.as_view(), name='employee_leave_chart_api'),
    path('department_leave_chart-api/', views.DepartmentLeaveChartView.as_view(), name='department_leave_chart_api'),
    path('leave_type_chart-api/', views.LeaveTypeChartView.as_view(), name='leave_type_chart_api'),
    path('leave_over_period-api/', views.LeaveOverPeriodView.as_view(), name='leave_over_period_api'),
    path('leave_request_create-api/', views.LeaveRequestCreationAPIView.as_view(), name='leave_request_create_api'),
    path('leave-allocation-request-view-api/', views.LeaveAllocationRequestView.as_view(), name='leave-allocation-request-view-api'),
    path('leave-allocation-request-single-view-api/<int:req_id>/', views.LeaveAllocationRequestSingleView.as_view(), name='leave-allocation-request-single-view-api'),
    path('leave-allocation-request-create-api/', views.LeaveAllocationRequestCreateView.as_view(), name='leave-allocation-request-create-api'),
    path('leave-allocation-request-filter-api/', views.LeaveAllocationRequestFilterView.as_view(), name='leave-allocation-request-filter-api'),
    path('leave-allocation-request-update-api/<int:req_id>/', views.LeaveAllocationRequestUpdateView.as_view(), name='leave-allocation-request-update-api'),
    path('leave-requests-approve-api/<int:req_id>/', views.LeaveAllocationRequestApproveAPIView.as_view(), name='leave-requests-approve-api'),
    path('leave-requests-reject-api/<int:req_id>/', views.LeaveAllocationRequestRejectAPIView.as_view(), name='leave-requests-reject-api'),
    path('leave-requests-delete-api/<int:req_id>/', views.LeaveAllocationRequestDeleteAPIView.as_view(), name='leave-requests-delete-api'),
    path('leave-assigned-select-api/', views.AssignedLeaveSelectAPIView.as_view(), name='leave-assigned-select-api'),
    path('leave-assigned-select-filter-api/', views.AssignedLeaveSelectFilterAPI.as_view(), name='assigned_leave_select_filter'),
    path('leave-requests-bulk-delete-api/', views.LeaveRequestBulkDeleteAPIView.as_view(), name='leave-requests-bulk-delete-api'),
    path('leave-requests-select-api/', views.LeaveRequestSelectAPIView.as_view(), name='leave-requests-select-api'),
    path('leave-requests-select-filter-api/', views.LeaveRequestSelectFilterAPIView.as_view(), name='leave-requests-select-filter-api'),
    path('user-requests-bulk-delete-api/', views.UserRequestBulkDeleteAPI.as_view(), name='user-requests-bulk-delete-api'),
    path('user-requests-select-api/', views.UserRequestSelectAPIView.as_view(), name='user-requests-select-api'),
    path('user-requests-select-filter-api/', views.UserRequestSelectFilterAPIView.as_view(), name='user-requests-select-filter-api'),
    path('employee-available-leave-count-api/', views.EmployeeAvailableLeaveCountAPIView.as_view(), name='employee-available-leave-count-api'),
    path('leave-cut-available-leave-api/<int:instance_id>/', views.CutAvailableLeaveAPI.as_view(), name='leave-cut-available-leave-api'),
    path('leave-create-comment-api/<int:leave_id>/', views.CreateLeaveRequestCommentAPIView.as_view(), name='leave-create-comment-api'),
    path('leave-requests-comments-view-api/<int:leave_id>/', views.ViewLeaveRequestCommentAPI.as_view(), name='leave-requests-comments-view-api',),
    path('leave-create-allocation-comment-api/<int:leave_id>/', views.CreateAllocationRequestCommentAPIView.as_view(), name='leave-create-allocation-comment-api'),
    path('leave-view-allocation-comment-api/<int:leave_id>/', views.ViewAllocationRequestCommentAPIView.as_view(), name='leave-view-allocation-comment-api'),
    path('leave-delete-allocation-comment-api/<int:comment_id>/', views.DeleteAllocationRequestCommentAPIView.as_view(), name='leave-delete-allocation-comment-api'),
    path('leave-delete-allocation-comment-file-api/', views.DeleteAllocationCommentFileAPIView.as_view(), name='leave-delete-allocation-comment-file-api'),
    path('leave-view-clashes-api/<int:leave_request_id>/', views.ViewClashesAPIView.as_view(), name='leave-view-clashes-api'),
    path('leave-compensatory-settings-api/', views.CompensatoryLeaveSettingsAPIView.as_view(), name='leave-compensatory-settings-api'),
    path('leave-enable-compensatory-api/', views.EnableCompensatoryLeaveAPIView.as_view(), name='leave-enable-compensatory-api'),
    path('leave-request-comment-delete-api/<int:comment_id>/', views.DeleteLeaveRequestCommentAPIView.as_view(), name='leave-request-comment-delete-api'),
    path('leave-comment-file-delete-api/', views.DeleteCommentFileAPIView.as_view(), name='leave-comment-file-delete-api'),
    path('get-leave-attendance-dates-api/', views.GetLeaveAttendanceDatesAPI.as_view(), name='get-leave-attendance-dates-api'),
    path('delete-comment-compensatory-file-api/', views.DeleteCommentCompensatoryFileAPIView.as_view(), name='delete-comment-compensatory-file-api'),
    path('delete-request-compensatory-comment-api/<int:comment_id>/', views.DeleteLeaverequestCompensatoryCommentAPIView.as_view(), name='delete-request-compensatory-comment-api'),
    path('view-compensatory-leave-api/', views.ViewCompensatoryLeaveAPIView.as_view(), name='view-compensatory-leave-api'),
    path('filter-compensatory-leave-api/', views.FilterCompensatoryLeaveAPIView.as_view(), name='filter-compensatory-leave-api'),
    path('create-compensatory-leave-api/', views.CompensatoryLeaveRequestCreate.as_view(), name='create-compensatory-leave-api'),
    path('delete-compensatory-leave-api/<int:comp_id>/', views.DeleteCompensatoryLeaveRequestView.as_view(), name='delete-compensatory-leave-api'),
    path('approve-compensatory-leave-api/<int:comp_id>/', views.ApproveCompensatoryLeaveAPIView.as_view(), name='approve-compensatory-leave-api'),
    path('leave-request-create-api/', views.LeaveRequestCreateAPI.as_view(), name='leave-request-create-api'),    
    path('leave-requestupdate-api/<int:id>/', views.LeaveRequestUpdateAPIView.as_view(), name='leave-requestupdate-api'),
    path('update-compensatory-leave-api/<int:comp_id>/', views.UpdateCompensatoryLeaveView.as_view(), name='update-compensatory-leave-api'),
    path('leave-requests-export-api/', views.LeaveRequestsExportAPIView.as_view(), name='leave-requests-export-api'),
    path('reject-compensatory-leave-api/<int:comp_id>/', views.RejectCompensatoryLeaveRequestView.as_view(), name='reject-compensatory-leave-api'),
    path('compensatory-leave-individual-api/<int:comp_leave_id>/', views.CompensatoryLeaveIndividualView.as_view(), name='compensatory-leave-individual-api'),
    path('compensatory-leave-comments-api/<int:comp_leave_id>/', views.CompensatoryLeaveCommentView.as_view(), name='compensatory-leave-comments-api'),
    path('create-compensatory-leave-comment-api/<int:comp_leave_id>/', views.CreateCompensatoryLeaveCommentView.as_view(), name='create-compensatory-leave-comment-api'),
    
    #path('leave-allocation-request-approve-api/<int:req_id>/', views.LeaveAllocationRequestApproveAPIView.as_view(), name='leave-allocation-request-approve-api'),


]










