from django.urls import path
from . import views


urlpatterns = [
    path('attendance-validate-api/<int:attendance_id>/', views.AttendanceValidateAPIView.as_view(), name='attendance-validate-api'),
    path('attendance-create-api/', views.AttendanceCreateAPIView.as_view(), name='attendance-create-api'),
    path('attendance-list-api/', views.AttendanceListAPIView.as_view(), name='attendance-list-api'),
    path('attendance-view-api/', views.AttendanceAPIView.as_view(), name='attendance_api'),
    path('attendance-search-api/', views.AttendanceSearchAPIView.as_view(), name='attendance_search_api'),
    path('attendance-update-api/<int:obj_id>/', views.AttendanceUpdateAPIView.as_view(), name='attendance_update_api'),
    path('attendance-delete-api/<int:obj_id>/', views.AttendanceDeleteAPIView.as_view(), name='attendance-delete-api'),
    path('attendance-bulk-delete-api/', views.AttendanceBulkDeleteAPIView.as_view(), name='attendance-bulk-delete-api'),
    path('attendance-my-api/', views.ViewMyAttendanceAPIView.as_view(), name='view-my-attendance-api'),
    path('attendance-filter-api/', views.FilterOwnAttendanceAPIView.as_view(), name='filter-own-attendance-api'),
    path('attendance-overtime-create-api/', views.AttendanceOvertimeCreateAPIView.as_view(), name='attendance-overtime-create-api'),
    path('attendance-overtime-view-api/', views.AttendanceOvertimeViewAPIView.as_view(), name='attendance_overtime_view_api'),
    path('attendance-overtime-search-api/', views.AttendanceOvertimeSearchAPIView.as_view(), name='attendance_overtime_search_api'),
    path('attendance-overtime-update-api/<int:obj_id>/', views.AttendanceOverTimeUpdateAPIView.as_view(), name='attendance_overtime_update_api'),
    path('attendance-overtime-delete-api/<int:obj_id>/', views.AttendanceOverTimeDeleteAPIView.as_view(), name='attendance_overtime_delete_api'),
    path('attendance-activities-api/', views.AttendanceActivityListAPIView.as_view(), name='attendance_activity_list_api'),
    path('attendance-activities-search-api/', views.AttendanceActivitySearchAPIView.as_view(), name='attendance_activity_search_api'),
    path('attendance-activities-delete-api/<int:obj_id>/', views.AttendanceActivityDeleteAPIView.as_view(), name='attendance-activity-delete_api'),
    path('attendance-clock-in-api/', views.ClockInAPIView.as_view(), name='clock-in-api'),
    path('attendance-clock-out-api/', views.ClockOutAPIView.as_view(), name='clock-out-api'),
    path('attendance-late-come-early-out-api/', views.LateComeEarlyOutAPIView.as_view(), name='late-come-early-out-api'),
    path('attendance-late-come-early-out-search-api/', views.LateComeEarlyOutSearchAPIView.as_view(), name='late-come-early-out-search-api'),
    path('attendance-late-come-early-out-delete-api/<int:obj_id>/', views.LateComeEarlyOutDeleteAPIView.as_view(), name='late-come-early-out-delete-api'),
    path('attendance-validation-condition-create-api/', views.ValidationConditionCreateAPIView.as_view(), name='validation-condition-create-api'),
    path('attendance-validation-condition-update-api/<int:obj_id>/', views.ValidationConditionUpdateAPIView.as_view(), name='validation-condition-update-api'),
    path('attendance-validation-condition-delete-api/<int:obj_id>/', views.ValidationConditionDeleteAPIView.as_view(), name='validation-condition-delete-api'),
    path('attendance-validate-bulk-api/', views.ValidateBulkAttendanceAPI.as_view(), name='validate-bulk-attendance-api'),
    path('attendance-validate-api/<int:obj_id>/', views.ValidateAttendanceAPIView.as_view(), name='validate-attendance-api'),
    path('attendance-revalidate-api/<int:obj_id>/', views.RevalidateAttendanceAPIView.as_view(), name='revalidate-attendance-api'),
    path('attendance-approve-overtime-api/<int:obj_id>/', views.ApproveOvertimeAPIView.as_view(), name='approve-overtime-api'),
    path('attendance-approve-bulk-overtime-api/', views.ApproveBulkOvertimeAPIView.as_view(), name='approve-bulk-overtime-api'),
    path('attendance-dashboard-api/', views.DashboardAPIView.as_view(), name='attendance-dashboard-api'), 
    path('attendance-dashboard-attendance-api/', views.DashboardAttendanceAPIView.as_view(), name='dashboard-attendance-api'),
    path('validate-attendance-request-api/<int:attendance_id>/', views.ValidateAttendanceRequestAPI.as_view(), name='validate-attendance-request-api'),
    path('approve-validate-attendance-request-api/<int:attendance_id>/', views.ApproveValidateAttendanceRequestAPIView.as_view(), name='approve-validate-attendance-request-api'),
    path('cancel-attendance-request-api/<int:attendance_id>/', views.CancelAttendanceRequestAPIView.as_view(), name='cancel-attendance-request-api'),
    path('bulk-approve-attendance-request-api/', views.BulkApproveAttendanceRequestAPIView.as_view(), name='bulk-approve-attendance-request-api'),
    path('bulk-reject-attendance-request-api/', views.BulkRejectAttendanceRequestAPIView.as_view(), name='bulk-reject-attendance-request-api'),  
    path('edit-validate-attendance-api/<int:attendance_id>/', views.EditValidateAttendanceAPI.as_view(), name='edit-validate-attendance-api'),
    path('get-employee-shift-api/', views.GetEmployeeShiftAPIView.as_view(), name='get-employee-shift-api'),
    path('attendance-request-changes-api/<int:attendance_id>/', views.AttendanceRequestChangesAPIView.as_view(), name='attendance-request-changes-api'),
    path('activity-single-view-api/<int:obj_id>/', views.ActivitySingleView.as_view(), name='activity-single-view-api'),
    path('attendance-activity-bulk-delete-api/', views.AttendanceActivityBulkDeleteView.as_view(), name='attendance-activity-bulk-delete-api'),
    path('late-in-early-out-single-view-api/<int:obj_id>/', views.LateInEarlyOutSingleView.as_view(), name='late-in-early-out-single-view-api'),
    path('late-come-early-out-bulk-delete-api/', views.LateComeEarlyOutBulkDeleteView.as_view(), name='late-come-early-out-bulk-delete-api'),
    path('request-attendance-api/', views.RequestAttendanceAPIView.as_view(), name='request-attendance-api'),
    path('request-edit-attendance-api/', views.EditRequestAttendanceAPI.as_view(), name='request-attendance-api'),

    path('request-attendance-view-api/', views.RequestAttendanceView.as_view(), name='request-attendance-view-api'),
    path('hour-attendance-select-api/', views.HourAttendanceSelectView.as_view(), name='hour-attendance-select-api'),
    path('hour-attendance-select-filter-api/', views.HourAttendanceSelectFilterView.as_view(), name='hour-attendance-select-filter-api'),
    path('work-records-api/', views.WorkRecordsView.as_view(), name='work-records-api'),
    path('work-records-change-month-api/', views.WorkRecordsChangeMonthView.as_view(), name='work-records-change-month-api'),
    path('create-attendancerequest-comment-api/<int:attendance_id>/', views.AttendanceRequestCommentAPIView.as_view(), name='create-attendancerequest-comment-api'),
    path('view-attendancerequest-comment-api/<int:attendance_id>/', views.AttendanceRequestCommentView.as_view(), name='view-attendancerequest-comment-api'),
    path('delete-attendancerequest-comment-api/<int:comment_id>/', views.DeleteAttendanceRequestCommentView.as_view(), name='delete-attendancerequest-comment-api'),
    path('department-overtime-chart-api/', views.DepartmentOvertimeChartView.as_view(), name='department-overtime-chart-api'),
    path('validated-attendances-table-api/', views.ValidatedAttendancesTableView.as_view(), name='validated-attendances-table-api'),
    path('user-request-one-view-api/<int:id>/', views.UserRequestOneView.as_view(), name='user-request-one-view-api'),   
    path('pending-hours-api/', views.PendingHoursView.as_view(), name='pending-hours-api'),
    path('create-grace-time-api/', views.GraceTimeCreateView.as_view(), name='create-grace-time-api'),
    path('update-grace-time-api/<int:grace_id>/', views.GraceTimeUpdateView.as_view(), name='update_grace_time'),
    path('delete-grace-time-api/<int:grace_id>/', views.GraceTimeDeleteView.as_view(), name='delete-grace-time-api'),
    path('assign-shift-api/<int:grace_id>/', views.GraceTimeAssignView.as_view(), name='assign-shift-api'),
    path('own-attendance-sort-api/', views.OwnAttendanceSortView.as_view(), name='own-attendance-sort-api'),
    path('attendance-activity-export-api/', views.AttendanceActivityExportView.as_view(), name='attendance-activity-export-api'),
    path('late-come-early-out-export-api/', views.LateComeEarlyOutExportView.as_view(), name='late_come_early_out_export'),
    path('attendance-account-export-api/', views.AttendanceAccountExportView.as_view(), name='attendance-account-export-api'),
    path('cut-available-leave-api/<int:instance_id>/', views.CutAvailableLeaveView.as_view(), name='cut-available-leave-api'),



]
